//Error types
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

//User types
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

//Project types
export const GET_PROJECTS = 'GET_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const PROJECTS_LOADING = 'PROJECTS_LOADING'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const SHARE_PROJECT = 'SHARE_PROJECT'
export const GET_SHARED_PROJECTS = 'GET_SHARED_PROJECTS'
export const LEAVE_SHARED_PROJECT = 'LEAVE_SHARED_PROJECT'
export const CLEAR_SHARE = 'CLEAR_SHARE'
export const FADE_OFF_SHARE = 'FADE_OFF_SHARE'
export const FADE_ON_SHARE = 'FADE_ON_SHARE'
export const CHECK_PROJECT_AUTH = 'CHECK_PROJECT_AUTH'
export const CLEAR_PROJECT = 'CLEAR_PROJECT'
export const GET_COLLABORATORS = 'GET_COLLABORATORS'

//Issue types
export const CREATE_ISSUE = 'CREATE_ISSUE'
export const GET_ISSUES = 'GET_ISSUES'
export const ISSUES_LOADING = 'ISSUES_LOADING'
export const DELETE_ISSUE = 'DELETE_ISSUE'
export const EDIT_ISSUE = 'EDIT_ISSUE'
export const CLOSE_ISSUE = 'CLOSE_ISSUE'
export const GET_SINGLE_ISSUE = 'GET_SINGLE_ISSUE'
export const CLEAR_ISSUE = 'CLEAR_ISSUE'
export const ISSUE_ERROR = 'ISSUE_ERROR'
export const DELETE_MANY_ISSUES = 'DELETE_MANY_ISSUES'
export const EDIT_ISSUE_CANCEL = 'EDIT_ISSUE_CANCEL'
export const CLEAR_ALL_ISSUES = 'CLEAR_ALL_ISSUES'
